backend:
  name: 'git-gateway'
  branch: 'main'
publish_mode: 'editorial_workflow'
media_folder: 'content/media'
public_folder: './'
collections:
  - name: 'website'
    label: 'Website'
    files:
      - name: 'content'
        label: 'Content'
        file: 'content/website.json'
        extension: 'json'
        fields:
          - name: 'meta_title'
            label: 'HTML Title'
            widget: 'string'
          - name: 'meta_description'
            label: 'HTML Description'
            widget: 'text'
          - name: 'meta_website'
            label: 'Website URL'
            widget: 'string'
          - name: 'markdown_body'
            label: 'Body'
            widget: 'markdown'
          - name: 'markdown_footer'
            label: 'Footer'
            widget: 'markdown'
