backend:
  name: 'git-gateway'
  branch: 'main'
publish_mode: 'editorial_workflow'
media_folder: 'content/media'
public_folder: './'
collections:
  - name: 'website'
    label: 'Website'
    files:
      - name: 'content'
        label: 'Content'
        file: 'content/website.json'
        extension: 'json'
        fields:
          - name: 'meta_title'
            widget: 'string'
            label: 'HTML Title'
          - name: 'meta_description'
            widget: 'string'
            label: 'HTML Description'
          - name: 'booking_url'
            widget: string
            label: 'URL for Bookings'
          - name: 'website_headline'
            widget: 'text'
            label: 'Website Headline'
          - name: 'schedule_headline'
            widget: 'string'
            label: 'Schedule Headline'
          - name: 'schedule_items'
            widget: 'list'
            label: 'Schedule Items'
            fields:
              - name: schedule_item
                widget: 'string'
                label: 'Schedule Item'
          - name: 'markdown_about'
            widget: 'markdown'
            label: 'About'
          - name: 'about_picture_description'
            widget: 'string'
            label: 'Photo Description'
          - name: 'map_url'
            widget: 'string'
            label: 'URL for Maps'
          - name: 'address'
            widget: 'text'
            label: 'Address'
          - name: 'social_url'
            widget: 'string'
            label: 'URL for Social'
          - name: 'phone_number'
            widget: 'string'
            label: 'Phone Number'
          - name: 'email_address'
            widget: 'string'
            label: 'Email Address'
          - name: 'markdown_footer'
            widget: 'markdown'
            label: 'Footer'
          - name: 'business_name'
            widget: 'hidden'
            default: 'Timmy Taper’s Barbershop'
          - name: 'meta_website'
            widget: 'hidden'
            default: 'https://timmytapersbarbershop.co.uk'
          - name: 'social_account'
            widget: 'hidden'
            default: '@timmytapersbarbershop'
          - name: 'i18n_booking_action'
            widget: 'hidden'
            default: 'Book now'
          - name: 'i18n_booking_action_alt'
            widget: 'hidden'
            default: 'Bookings'
          - name: 'i18n_email'
            widget: 'hidden'
            default: 'Email Address'
          - name: 'i18n_map'
            widget: 'hidden'
            default: 'on Google Maps'
          - name: 'i18n_phone'
            widget: 'hidden'
            default: 'Phone Number'
          - name: 'i18n_social'
            widget: 'hidden'
            default: 'Instagram Account'
